FROM rocker/shiny:4.3.2

WORKDIR /srv/shiny-server/esg-platform

COPY r_dashboard/install_packages.R .
RUN Rscript install_packages.R

COPY r_dashboard/app/ .
COPY r_dashboard/reports /srv/shiny-server/esg-platform/reports

ENV ESG_API_BASE=http://api:8000

EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/esg-platform', host='0.0.0.0', port=3838)"]
